---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: ..
  fileserver_config_path: puppet/fileserver.conf
  files_path: puppet/files
  puppet_debug: true

platforms:
  - name: debian-6.0.8
  - name: debian-7.2.0
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: master
  - name: slave
