---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: ..
  fileserver_config_path: puppet/fileserver.conf
  files_path: puppet/files
  puppet_debug: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: master
  - name: slave
